# Site settings
title: Workshop on Deep Probabilistic Models, 2016
email: andreas.damianou@sheffield.ac.uk
description: > # this means to ignore newlines until "baseurl:"
  This is the third informal round table on Deep Probabilistic models. This meeting is sponsored by EPSRC grant number EP/N014162/1, "Deep Probabilistic Models for Making Sense of Unstructured Data"
baseurl: "/deepp16" # the subpath of your site, e.g. /blog/
url: "http://gpss.cc" # the base hostname & protocol for your site
twitter_username: DataScienceShef
github_username:  gpschool


# Build settings
future: true

permalink: "/:categories/:title.html"
banner: 

analytics:
 google:
   tracking_id: UA-62991754-1

youtube:
  height: 315
  width: 560

conference:
  room: Mercer Room
  venue: Royal Society, 6-9 Carlton House Terrace
  location: London, UK
  name: Workshop on Deep Probabilistic Models
  year: 2016
  month: September
  dates:
  - 2016-06-08
  draft: false # set to True if the programme is draft only.
  hosts:
  organizers:
  - name: Andreas Damianou
    url: "http://adamian.github.io/"
  - name: Zoubin Ghahramani
    url: "http://mlg.eng.cam.ac.uk/zoubin/"
  - name: Neil Lawrence
    url: "http://inverseprobability.com"

map:
  show: False
  mapbox:
    latitude: # latitude of map center
    longitude: # longitude of map center
    map_id: # mapbox id
    access_token: # mapbox access token
    zoom_level: 17
    width: 100%
    height: 500px
